language: python 
sudo: false
before_install:
- export PATH=~/miniconda/bin:$PATH
- devtools/ci/travis/install_miniconda.sh
- conda config --set always_yes true
- conda config --add channels conda-forge
- conda install -q conda-build

script:
- conda build -q devtools/conda-recipe

