language: python 
sudo: false
before_install:
- devtools/ci/travis/install_miniconda.sh
- conda config --set always_yes true
- conda config --add channels omnia # for pytest-ipynb
- conda config --add channels conda-forge
- conda install -q ipywidgets 

script:
- conda build -q devtools/conda-recipe

