package:
  name: progress_reporter
  version: "dev"

source:
  path: ../../

build:
  noarch_python: True
  number: 0
  script: python setup.py sdist; pip install dist/*


requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - python
    - tqdm

test:
  imports:
    - progress_reporter
  source_files:
    - tests/
  requires:
    - pytest
    - nbval
    - ipywidgets
    - notebook
  commands:
    - pytest --nbval -vv tests
